import type { AppProps } from 'next/app';
import Head from 'next/head';

import { ScreenProvider } from '@/contexts/screen';
import { ThemeProvider } from '@/contexts/theme';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider>
      <ScreenProvider>
        <Head>
          <title>Rick and Morty</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, viewport-fit=cover"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </ScreenProvider>
    </ThemeProvider>
  );
}
